### ISSUE TITLE
92 - Import Sample Brand Data

### ISSUE THREAD

**Issue by GetinetA** [GetinetA/shopme#71]
<img width="910" alt="92 1_import-sample_brand_data" src="https://user-images.githubusercontent.com/8474891/137603313-72585b5d-95e5-4aa2-ba6b-2a835505f01a.png">

<img width="912" alt="92 2_import-sample_brand_data" src="https://user-images.githubusercontent.com/8474891/137603316-ce5db939-9d3e-433f-82f7-fed1e02426f0.png">

**Comment by GetinetA** [comment]
### SQL statements
1- Execute the following queries in step

SET foreign_key_checks = 0;

truncate table brands_categories;
truncate table brands;

SET foreign_key_checks = 1;

2 - Then import the data (MySQL)

- From the menu select Server -> Data Import
- Select 'Import from Self-Contained File' checkbox
- Enter/choose the sql file to import
- Select a schema from 'Default Target Schema' drop down list
- Choose 'Dump Data Only'
- Click 'Start Import' button
- end

3 - Copy the image folder to the project

**Comment by romanciucadrian** [comment]
can you give me the password for the archive plz ?

**Comment by GetinetA** [comment]
This for Udemy course, the instructor is the one who gives access to that. Why not you register? now it is on sell $12
https://www.udemy.com/course/spring-boot-e-commerce-ultimate/
